# Generated by Django 4.2.7 on 2025-11-26 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(verbose_name='Descripción del pedido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo para retirar'), ('RETRIEVED', 'Retirado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
