# Generated by Django 4.2.7 on 2025-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
